[package]
name = "generic-global-variables"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anymap2 = "0.13.0"
parking_lot = "0.11.2"
once_cell = "1.8.0"
